replicaCount: 1
image:
  repository: 899631475351.dkr.ecr.us-east-2.amazonaws.com/ai-inference-service
  tag: "aefe19b7f5bbcb13d28f3e0d93ea6bc505829629"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8001
  targetPort: 8001
env:
  LOG_LEVEL: "info"
  MODEL_NAME: "stub-model"
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15
