replicaCount: 3

image:
  repository: 899631475351.dkr.ecr.us-east-2.amazonaws.com/ai-inference-service
  tag: "695bb7995707825f2ce914033790d6df9a0e0733"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8001
  targetPort: 8001

env:
  LOG_LEVEL: "info"
  MODEL_NAME: "stub-model"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  memory:
    averageUtilization: 70
