replicaCount: 1
image:
  repository: 899631475351.dkr.ecr.us-east-2.amazonaws.com/api-service
  tag: "f56f66c61ca248f9be1213e48e6a564ae1385324"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
env:
  AI_SERVICE_URL: "http://ai-inference-service:8001"
  LOG_LEVEL: "info"
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15
