replicaCount: 1
image:
  repository: 899631475351.dkr.ecr.us-east-2.amazonaws.com/api-service
  tag: "31726869c2210238468393b69a6c267c8f29534f"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
env:
  AI_SERVICE_URL: "http://ai-inference-service:8001"
  LOG_LEVEL: "info"
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 15
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpu:
    averageUtilization: 70
